In [2]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

**1. Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:**


$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [3]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


**2. Дан оператор поворота на 180 градусов, задаваемый матрицей:**

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.

Найдем собственные векторы вида $\begin{pmatrix} x_{1}\\ x_{2} \end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:,

$$\begin{pmatrix} -1 & 0\\  0 & -1 \end{pmatrix}
\begin{pmatrix} x_{1}\\ x_{2} \end{pmatrix}=
\lambda
\begin{pmatrix} x_{1}\\ x_{2} \end{pmatrix}$$


Получим
$$\begin{cases} -x_{1}+0\cdot x_{2}= x_{1},\\ 0\cdot x_{1}-x_{2}= x_{2}. \end{cases}$$ 

$$\begin{cases}\ - x_{1} = x_{1}, \\\ - x_{2} = x_{2}. \end{cases}$$ 
   
**Очевидно, что при лямбда равном -1, система имеет множество решений**

In [5]:
a_2 = np.array([[-1, 0], [0, -1]])
w_2, v_2 = np.linalg.eig(a_2)

print(f'Матрица A:\n{a_2}')
print(f'Собственные значения:\n{w_2}')
print(f'Собственные векторы:\n{v_2}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


**3. Пусть линейный оператор задан матрицей:**

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix} 1 & 1\\ -1 & 3 \end{pmatrix}
\begin{pmatrix} 1\\ 1 \end{pmatrix}=\lambda
\begin{pmatrix} 1\\ 1 \end{pmatrix}$$
    
Из этого следует: 
$$\begin{cases} 1+1=1\cdot\lambda \\ -1+3 = 1\cdot \lambda \end{cases}
\Rightarrow
\begin{cases} \lambda=2\\ \lambda=2 \end{cases}$$

Таким образом, вектор  $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение $\lambda=2.$

In [7]:
a_3 = np.array([[1, 1], [-1, 3]])
w_3, v_3 = np.linalg.eig(a_3)

print(f'Матрица A:\n{a_3}')
print(f'Собственные значения:\n{w_3}')
print(f'Собственные векторы:\n{v_3}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


**4. Пусть линейный оператор задан матрицей:**

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0 \\ 0 & 0 & 3 \end{pmatrix}
\begin{pmatrix} 3\\ -3 \\ -4 \end{pmatrix}=\lambda
\begin{pmatrix} 3\\ -3 \\ -4 \end{pmatrix}$$

Из этого следует: 
$$\begin{cases} 0-9+0=3\cdot\lambda \\ 9+0+0 = -3\cdot \lambda \\ 0+0+(-12) = -4\cdot \lambda \end{cases}
\Rightarrow
\begin{cases} -9 = 3\lambda\\ 9 = -3\lambda\\ -12 = -4\lambda \end{cases}
\Rightarrow
\begin{cases} -3 = \lambda\\ -3 = \lambda\\ 3 = \lambda \end{cases}$$

**Таким образом, вектор  $x=(3, -3, 4)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение $\lambda=-3.$**

In [8]:
a_4 = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w_4, v_4 = np.linalg.eig(a_4)

print(f'Матрица A:\n{a_4}')
print(f'Собственные значения:\n{w_4}')
print(f'Собственные векторы:\n{v_4}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]


In [10]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([[3], [-3], [-4]])
z = np.dot(a, x)
z

array([[ -9],
       [  9],
       [-12]])