In [1]:
import numpy as np

**1.1. Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:**

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


Если количество столбцов в первой матрице соответствует количеству строк во второй, то можно сказать, что произведение матриц  определено. <br>
а) произведение матриц неопределено;<br>
б) произведение матриц определено, размерность полученной матрицы 2×3;<br>
в) произведение матриц определено, размерность полученной матрицыь 8×8;<br>
г) произведение матриц определено, размерность полученной матрицы 4×4.

**1.2. Найдите сумму и произведение матриц** $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Сумма A + B\n{A + B}\n')
print(f'Произведение AB\n{np.dot(A, B)}')

Сумма A + B
[[ 5 -3]
 [ 3  5]]

Произведение AB
[[  4 -11]
 [ 12  -3]]


**1.3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию** $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Комбинация 3𝐴−2𝐵+4𝐶\n{3*A -2*B + 4*C}')

Комбинация 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


**1.4. Дана матрица** $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.


In [4]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица At\n{A.T}')
print(f'Матрица A*At\n{np.dot(A, A.T)}')
print(f'Матрица At*A\n{np.dot(A.T, A)}')

Матрица At
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*At
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица At*A
[[45  0]
 [ 0 14]]


_______________________________________________________________________________________________________________________________

**2.1 Вычислите определитель:**

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [5]:
a = np.array([[np.sin(0), -np.cos(0)], [np.cos(0), np.sin(0)]])
print(f'Матрица а:\n{a}\n'
      f'Определитель а:  {np.linalg.det(a):.0f}\n')  

Матрица а:
[[ 0. -1.]
 [ 1.  0.]]
Определитель а:  1



In [6]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица б:\n{b}\n'
      f'Определитель б:  {np.linalg.det(b):.0f}\n')

Матрица б:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель б:  180



In [7]:
v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица в:\n{v}\n\n'
       f'Определитель в:  {np.linalg.det(v):.0f}\n')

Матрица в:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Определитель в:  -0



**2.2. Определитель матрицы $A$ равен $4$. Найдите:**

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) Согласно свойству для квадратных матриц одинакового размера,
$det(AB)=detA\cdot detB.$<br> 
Поэтому $det(A^{2})$ = $det(A)*det(A)$ = 16.

б) $det(A^{T})$;<br>
Определитель транспонированной матрицы равен определителю исходной: $detA^{T}=detA.$ = 16,

в) $det(2A)$
Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. Значит, для матрицы порядка n, n строк будут умножены на 2, и определитель увелится в 2^{n} раз.<br>
$det(2A) = detA *2^{n} = 16$ 

In [8]:
a = np.array([[5, 2], [3, 2]]) #возьмём для примера такую матрицу
b = np.dot(a, a)
c = 2*a
print(f'Матрица:\n{b}')
print(f'Матрица:\n{c}')
print(f'а) {np.linalg.det(b):.0f}')
print(f'б) {np.linalg.det(a.T):.0f}')
print(f'в) {np.linalg.det(c):.0f}')

Матрица:
[[31 14]
 [21 10]]
Матрица:
[[10  4]
 [ 6  4]]
а) 16
б) 4
в) 16


**2.3. Докажите, что матрица:**

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [9]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель равен {np.linalg.det(a):.0f}, значит, матрица вырожденая')

Определитель равен 0, значит, матрица вырожденая


**2.4. Найдите ранг матрицы:**

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [10]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы a: {r}')

Ранг матрицы a: 2


In [11]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
q = [2, 3, 5, 6]

a_1 = np.array([x, y, z, q])
r = np.linalg.matrix_rank(a_1)

print(f'Ранг матрицы б: {r}')

Ранг матрицы б: 3
