In [1]:
import numpy as np
from numpy.linalg import norm

**1.1. Исследуйте на линейную зависимость:**

$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$


Мы можем выразить 4й элемент через 3 других: 
$$f_{4}(x)=f_{3}(x) - f_{1}(x) - f_{2}(x)$$
Соответственно, можно сделать вывод о присутствии ленийной зависимости.

_____________________________________________________________________________________________________________________________

**1.2. Исследуйте на линейную зависимость:**
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}$$

Мы можем выразить 4й элемент через 3 других: 
$$f_{4}(x)=f_{3}(x) + 2f_{2}(x) - f_{1}(x)*1/2$$
Соответственно, можно сделать вывод о присутствии ленийной зависимости.

_____________________________________________________________________________________________________________________________

**1.3. Найдите координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.**

$$\quad x = (0.5\cdot b1,1\cdot b2,3\cdot b3)=
(\frac{1}{2}\cdot b_1, b_2, 3\cdot b_3) = (0.5, 1, 3)$$

In [2]:
b1 = np.array([0, 0, 10])
b2 = np.array([2, 0, 0])
b3 = np.array([0, 1, 0])
x = np.array([2, 3, 5])

In [3]:
y = np.array([b1, b2, b3]).T
y

array([[ 0,  2,  0],
       [ 0,  0,  1],
       [10,  0,  0]])

In [4]:
y_1 = np.linalg.inv(y)
y_1

array([[0. , 0. , 0.1],
       [0.5, 0. , 0. ],
       [0. , 1. , 0. ]])

In [5]:
z = np.dot(y_1, x)
z

array([0.5, 1. , 3. ])

_____________________________________________________________________________________________________________________________

**1.4. Найдите координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:**

а) в базисе $1$, $x$, $x^{2}$;

б) в базисе $x^{2}$, $x-1$, $1$.

***Вектор ($3x^2, -2x, 2$)***
<br><br>

**В базисе а ($1$, $x$, $x^{2}$) :**
$b_{1}=(1, 0, 0)$, $b_{2}=(0, x, 0)$, $b_{3}=(0, 0, x^2)$

**Ответ: $(2, -2, 3)$**
<br>
<br>
<br>
**В базисе б ($x^{2}$, $x-1$, $1$) : $b_{1}=(x^2, 0, 0)$, $b_{2}=(0, x - 1, 0)$, $b_{3}=(0, 0, 1)$**

**Ответ: $(3, -2, 0)$**

_____________________________________________________________________________________________________________________________

**1.5. Установите, считается ли линейным подпространством:**

а) совокупность всех векторов трёхмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю

Пусть у нас будут векторы (0, a, b), (0, c, d), (0, 0, b). Третий является частным случаем первого и второго множества, так что его можно не проверять.
 
$$(0, a, b)+(0, c, d) = (0, a+c, b+d),$$ $$\alpha\cdot (0, a, b) = (0, \alpha a, \alpha b).$$
 
 
Полученные векторы также принадлежат указанному в задании множеству всех векторов вида $(0, a, b)$, то есть это множество считается подпространством линейного пространства $\mathbb{R}^{3}$. Аналогичное доказательство будет для второго подпространства. Поэтому совокупность всех этих подпространств также будет являться линейной.

_____________________________________________________________________________________________________________________________

**2.1. Найдите скалярное произведение векторов $x, y \in \mathbb{R}$:** <br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

In [6]:
#a
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
print(f'Скалярное произведение x и y:\n{np.dot(x, y)}')

Скалярное произведение x и y:
33


In [7]:
#б
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
print(f'Скалярное произведение x и y:\n{np.dot(x, y)}')

Скалярное произведение x и y:
-23


_____________________________________________________________________________________________________________________________

**2.2._ Найдите нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.**

In [8]:
x = np.array([4, 2, 4])
y = np.array([12, 3, 4])
print(f'Манхэттенская норма вектора x:  {norm(x, ord=1)}')
print(f'Манхэттенская норма вектора y:  {norm(y, ord=1)}')
print(f'Евклидова норма вектора x:  {norm(x, ord=2)}')
print(f'Евклидова норма вектора y:  {norm(y, ord=2)}')

Манхэттенская норма вектора x:  10.0
Манхэттенская норма вектора y:  19.0
Евклидова норма вектора x:  6.0
Евклидова норма вектора y:  13.0


In [9]:
cos_phi = np.dot(x, y) / norm(x) / norm(y)
print(f'Косинус угла между векторами:  {cos_phi}')
print(f'Угол между векторами: {np.arccos(cos_phi)}')

Косинус угла между векторами:  0.8974358974358974
Угол между векторами: 0.4568740035326613


_____________________________________________________________________________________________________________________________

**2.3. Определите, будет ли линейное пространство евклидовым, если за скалярное произведение принять:**<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?<br>

Евклидово пространство должно подчиняться четырём аксиомам:<br>
1) $(x,y)=(y,x).$<br>
2) $(\lambda x, y)=\lambda(x, y).$<br>
3) $(x_{1}+x_{2},y)=(x_{1},y)+(x_{2},y).$<br>
4) $(x, x)\geq0$, причём $(x,x)=0\Leftrightarrow x=0.$

**а) произведение длин векторов:**

1) длины векторов это обычные числа, поэтому от перестановки их ничего не изменится<br>
2) аналогично<br>
3) для чисел эта аксиома соблюдается<br>
4) число в квадрате всегда больше равно 0<br>
**Ответ:** пространство будет евклидовым

**б) утроенное обычное скалярное произведение векторов:**

1) 3(𝑥,𝑦)=3(𝑦,𝑥) = 3xycos(a)<br>
2) 3(𝜆𝑥,𝑦)=3𝜆(𝑥,𝑦) = 3𝜆xycos(a)<br>
3) 3(𝑥1+𝑥2,𝑦)= 3(𝑥1+𝑥2)𝑦cos(a) =3(𝑥1,𝑦)+3(𝑥2,𝑦)<br> 
4) 3(𝑥,𝑥)≥0, причем 3(𝑥,𝑥)=0⇔𝑥=0. <br>
**Ответ:** пространство будет евклидовым

_____________________________________________________________________________________________________________________________

**2.4. Выясните, какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$**:<br>
а) $(1,0,0),(0,0,1);$ <br>

Два вектора не могут образовать ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$

б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$

In [10]:
x = np.array([1/np.sqrt(2), -1/np.sqrt(2), 0])
y =  np.array([1/np.sqrt(2), 1/np.sqrt(2), 0])
z = np.array([0, 0, 1])

print(f'т.к. скалярное произведение равно {np.dot(x, np.dot(y, z))}, вектора x, y и z образуют ортонормированный базис')

т.к. скалярное произведение равно [0. 0. 0.], вектора x, y и z образуют ортонормированный базис


в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$

In [11]:
x_2 = np.array([1/2, -1/2, 0])
y_2 =  np.array([0, 1/2, 1/2])
z_2 = np.array([0, 0, 1])
evc_2 = x_2[0] * y_2[0] * z_2[0] + x_2[1] * y_2[1] * z_2[1] + x_2[2] * y_2[2] * z_2[2]

print(f'т.к. скалярное произведение равно {np.dot(x_2, np.dot(y_2, z_2))}, вектора x_2, y_2 и z_2 не образуют ортонормированный базис')

т.к. скалярное произведение равно [ 0.25 -0.25  0.  ], вектора x_2, y_2 и z_2 не образуют ортонормированный базис


г) $(1,0,0),(0,1,0),(0,0,1)$

In [12]:
x_3 = np.array([1, 0, 0])
y_3 =  np.array([0, 1, 0])
z_3 = np.array([0, 0, 1])
evc_3 = x_3[0] * y_3[0] * z_3[0] + x_3[1] * y_3[1] * z_3[1] + x_3[2] * y_3[2] * z_3[2]

print(f'т.к. скалярное произведение равно {np.dot(x_3, np.dot(y_3, z_3))}, вектора x_3, y_3 и z_3 образуют ортонормированный базис')

т.к. скалярное произведение равно [0 0 0], вектора x_3, y_3 и z_3 образуют ортонормированный базис
